### ISSUE TITLE
Turning from Popup menu

### ISSUE THREAD

**Issue by panyachu** [ENSL/NS#110]
When select one of leaf (especially distant leaves) from Popup menu tree , player turn left (or right) at a small angle.

**Comment by pierow** [comment]
Hi, can you share the NS version and m_rawinput value you're using? Mouse polling rate might help too. There's a few mouse issues with the popup menu and it's something we've been trying to fix for a while, but the initial issues stemming from the HL1 engine steampipe update makes it quite hard to fully fix. I'm not sure if we'll be able to make it much better.

Originally when HL1 got patched, ns 3.2 had issues with view rotating however much you moved the mouse when using the popup menu in regular input mode.  That was fixed for regular input I believe, but for raw input there's a kind of hacked in fix that toggles raw input off momentarily when the menu is opened so the mouse can be centered since we haven't found a way center the cursor with raw input on due to engine limitations.  Some setups don't handle this as well as most and there can be view rotation that occurs when it toggles this.

**Comment by panyachu** [comment]
Sorry, it was Unknownworlds official release v 3.2.
From this repository (both branch), or from NaturalSelectionLauncher I can't reproduce this.
