### ISSUE TITLE
Missing running animation on weapons.

### ISSUE THREAD

**Issue by EPIC3D** [ENSL/NS#143]
I am currently using 3.3b7 version and I noticed that when moving there is no back and forth movement on the weapons.
There are also some missing idle animation.  LMG for example never moves besides the firing and reloading animation.

Is this a settings issue? Because I looked in the setting and found nowhere to change this.

**Comment by pierow** [comment]
To fix this you'll want to go into your `userconfig.cfg` in the `ns` directory and change `cl_bob 0` into `cl_bob 1`. You can also just enter `cl_bob 1` into the console, but it won't last between map changes.

Thanks for reminding me about this. This fork of the game was originally for getting people into competitive games easier, so some of the config entries aren't ideal for a broader audience. I'll make this easier to change, and perhaps make it default again.

There is an `olddefaults.cfg` with all the defaults from NS 3.2 if you're interested, but I wouldn't recommend using everything in it, because there's things like old network rates and lighting settings that are intended to be used with the gamma ramp that doesn't work on modern OSes.

**Comment by EPIC3D** [comment]
Thank you for the reply.
I gave it a try and it produced choppy movement instead of smooth animation. If I hug a wall or a railing animation look closer how it supposed to be.  I tried it on another PC and it had the same issue. 3.3b7 default settings besides the cl_bob "1"

Here I recorded gameplay.
https://youtu.be/8t0YpNS_72Q
https://youtu.be/3s0fOqyla54

**Comment by pierow** [comment]
Sorry, my mistake. The correct command is `cl_bob 0.01`.

**Comment by EPIC3D** [comment]
> Sorry, my mistake. The correct command is cl_bob `0.01.`

Works perfectly. Thank you.

**Comment by pierow** [comment]
This has been fixed in the latest patch, and there's some new bob settings/presets now.
