### ISSUE TITLE
AMX?

### ISSUE THREAD

**Issue by GreatAbsoluteGod** [ENSL/NS#188]
Has support for AMX in the latest update been dropped?
For some reason, my listen server will not run AMX whatsoever.

**Comment by pierow** [comment]
It still works. You might need to update your amx and metmod versions or fix an installation issue. `meta list` in console should help determine if metamod is loaded and should return some info about if it tried to load AMX. Also check and make sure that your `liblist.gam` is still configured to start metamod. If it was overwritten when patching, then it won't try to load metamod.

The latest version of AMX updated for NS can be found here: https://github.com/pierow/amxmodx-ns/releases

I've been testing with this recent metamod release but I've had various versions of metamod including some of these releases complain about the NS version not being correct:
https://github.com/APGRoboCop/metamod-p/releases

**Comment by GreatAbsoluteGod** [comment]
> It still works. You might need to update your amx and metmod versions or fix an installation issue. `meta list` in console should help determine if metamod is loaded and should return some info about if it tried to load AMX. Also check and make sure that your `liblist.gam` is still configured to start metamod. If it was overwritten when patching, then it won't try to load metamod.
> 
> The latest version of AMX updated for NS can be found here: https://github.com/pierow/amxmodx-ns/releases
> 
> I've been testing with this recent metamod release but I've had various versions of metamod including some of these releases complain about the NS version not being correct: https://github.com/APGRoboCop/metamod-p/releases

Yeah, meta list returns nothing.
The DLL's are listed in the liblist. 

Though, typing "amxx plugins" does list some things.
However, it appears that they still aren't necessarily functional at all. 
Strange. 

Can you tell me which Metamod version you are **currently** using?

**Comment by pierow** [comment]
It's strange that `meta list` returns nothing but AMX seems to work in some capacity if it's returning a plugin list with `amxx plugins`. Does `amx_menu` open a white text menu on the left hand side of the screen in game? It's possible the version of metamod you have has issues with HL 25th anniversary if the issue has appeared with the new updates.

I'm using this metamod release:
https://github.com/APGRoboCop/metamod-p/releases/download/v1.21p42/metamod_1_21-p42-APG_i686.zip

And this AMX release:
https://github.com/pierow/amxmodx-ns/releases/download/amxx-ns3.3b9/amxx_1.8.2_win_ns3.3b9_full.zip

**Comment by GreatAbsoluteGod** [comment]
Still doesn't seem to work.
To make things clear.
I have things put > 

ns/addons/amxmodx 
ns/addons/metamod

Liblist has:
gamedll "addons\metamod\dlls\metamod.dll"
gamedll_linux "addons/metamod/dlls/metamod.so"
gamedll_osx "addons/metamod/dlls/metamod.dylib"


For more clarity at least as far as the console goes:


>] amx_menu
>Unknown command: amx_menu
>] amx_menu 
>Unknown command: amx_menu
>] amxx
>Usage: amxx < command > [ argument ]
>Commands:
  > version                - display amxx version info
  > gpl                    - print the license
  > plugins                - list plugins currently loaded
   >modules                - list modules currently loaded
   >cvars [ plugin ]       - list cvars registered by plugins
   >cmds [ plugin ]        - list commands registered by plugins
   >pause < plugin >       - pause a running plugin
   >unpause < plugin >     - unpause a previously paused plugin
>] amxx plugins
>Currently loaded plugins:
       >name                    version     author            file             status   
>0 plugins, 0 running


All of these things seem to be par for the course when originally installing amxmodx. 
And it appears that the amxx module still kind of functions, though without any use. 
I might just have to revert back to the previous version of NS just to make things work I guess..
Bummer because I really liked the addition of the new bots.

**Comment by GreatAbsoluteGod** [comment]
Another update:
I used an older metamod DLL and for some reason... 
Meta list seems to work now and even display some plugins..
But amxmodx itself.. still doesn't work.

**Comment by pierow** [comment]
It sounds like you're installing it correctly, but just to make sure, since other half-life mods, configurations, or plugins can interfere with things, please follow these steps:

1. Move your Half-Life folder to another location like your desktop for the time being so you don't lose your data
2. In steam, uninstall then reinstall Half-Life, making sure in its properties that Beta is set to "none"
3. Install NS into the fresh install of HL https://github.com/ENSL/NS/releases/download/v3.3b9/ns_v33b9_full.zip
4. Install this addon pack containing the metamod and AMX releases that I have confirmed works on my system. Confirm overwriting the `liblist.gam` file.
[ns-plugins-test.zip](https://github.com/user-attachments/files/16046290/ns-plugins-test.zip)
5. Confirm there's no additional launch parameters for Half-Life or NS in their steam properties.
6. Launch NS and create a listen server with "Create game". Do not use the "map" console command.
7. Try some of the commands mentioned above like `meta list`, `amxx plugins` and `amx_menu`. Some of these will say the command is unknown, but the proper output will be displayed above that.

Also, please let me know what operating system you're using. I've tested this on windows 10 and it works. I've also tested metamod and amx on windows and linux HLDS, but I have not tested it on a linux client listen server.

If those steps didn't work, it seems likely that there's some sort of external dependency issue. Another thing to try is perhaps testing the AMX 1.9 beta release, as it's compiled differently than the 1.8.2 build. https://github.com/pierow/amxmodx-ns/releases

More info on debugging metamod can be found here: http://metamod.org/metamod.html

If it's still not working, any and all console output from metamod and AMX with `debuglevel 42` set in the metamod `config.ini` would be helpful. I can also help you identify any external dependencies these addons use that you might not have installed.

**Comment by GreatAbsoluteGod** [comment]
Your plugins test worked immediately.
Wow.
I have no words.
It must have been the metamod version.
Thank you so much!
