### ISSUE TITLE
Process hangs on exit

### ISSUE THREAD

**Issue by pierow** [ENSL/NS#19]
Sometimes when quitting the game, the game either freezes until the process is killed, or the hl.exe stays running in the background after appearing to close.  This is an old bug that has existed for many years, before recent NS and HL1 updates.

This can be reproduced on windows I'm not sure if this applies to linux and osx as well.  Simply launch the game, load a map with `map ns_veil` , join a team and shoot your gun for a couple of seconds, then try to quit the game.  It should happen at least 1 out of 5 tries.  This is confirmed an issue with default settings as well as with NS 3.2.

**Comment by pierow** [comment]
![image](https://user-images.githubusercontent.com/6503238/103700771-f332f080-4f72-11eb-9567-7609e0cf3b1e.png)
A view in process explorer when the issue happens.

**Comment by RGreenlees** [comment]
This is caused by the Windows SDK being unable to unload the ancient version of FMOD in use. We can fix this by simply not trying to unload the library and letting Windows do it automatically during clean-up when the application terminates.

Since the library is only used for in-game music and ambient sounds, we can also simply not load FMOD at all if the user has both disabled.
