### ISSUE TITLE
func_nobuild issue

### ISSUE THREAD

**Issue by jirikivaari** [ENSL/NS#32]
Walking in func_nobuild lags the game. For example heating crate in ns_metal.

**Comment by NukemD** [comment]
If by "lag" you mean that collision detection on the func_nobuild entity is bad and causes rubber banding when you touch it, it has always been this way. I don't think the devs ever intended for func_nobuild to be able to interact with the player since its effects are infinitely tall on the Z axis (+/-4096) no matter how tall the actual func_nobuild brush is. Due to this behavior, you can have a pencil thin brush outside the play area that affects the play area where players will never be able to touch it. Early NS maps did this, but later NS maps started putting them inside the play area, where you have this problem.

A solution that I discovered around 12 years ago was to instead use a trigger_hurt brush, set to do 9999 damage with spawnflags of 8 (No Clients.) This solved all problems with func_nobuild, it would no longer affect clients movement and would stop the unwanted infinitely high no build volume that makes stacked maps impossible. Any marine or alien structure will be immediately destroyed if placed inside the trigger_hurt volume, or touching it if it falls into the volume. It does have the unwanted effect of lost resources of the destroyed building, but people quickly learn where they're not allowed to build.

I employed it in several of my maps with good success, one being ns_supersiege004d.

**Comment by jirikivaari** [comment]
Solution would be then to do some script to update the map ents without map decompilation.

**Comment by NukemD** [comment]
Best way to do it is to use ripent.exe to dump the entity list to a file and use a decompiled copy of the map to find func_nobuild entities. Converting everything blindly could lead to issues.

**Comment by pierow** [comment]
This was fixed in recent patches.
