### ISSUE TITLE
Chatbox eats inputs occasionally

### ISSUE THREAD

**Issue by jirikivaari** [ENSL/NS#45]
Chatbox eats inputs occasionally. I think its SDL related.

**Comment by pierow** [comment]
I wouldn't consider this trivial.  It happens about half of the time I type a message in game and when it happens it tends to repeatedly happen in the same message so it takes a while to sit there and try to correctly type a message.

**Comment by pierow** [comment]
Upon further testing it seems to me that the issue is that when backspace is pressed in it prevents any new keys from being entered until released. This is atypical for text input.

**Comment by Bacsu** [comment]
I didn't got the SDL_KEYDOWN event at the eventloop. Maybe because SDL get's also handled by HL and the KeyEvent gets called by the engine. Now we're taking a look if the function is called with a KeyDown event from HL and if we had non TextInput.
If so handle backspace.
 
- 

https://github.com/ENSL/NS/blob/d4e91fd005ba274701d962391d8ce5a2452ab8be/main/source/cl_dll/vgui_TeamFortressViewport.cpp#L2391

must be changed to
`m_chatPanel->KeyEvent(down);`

- 
https://github.com/ENSL/NS/blob/d4e91fd005ba274701d962391d8ce5a2452ab8be/main/source/ui/ChatPanel.h#L23

must be changed to 
`void KeyEvent(int iKeydown);`

- 
https://github.com/ENSL/NS/blob/d4e91fd005ba274701d962391d8ce5a2452ab8be/main/source/ui/ChatPanel.cpp#L211

function must be changed to

    void ChatPanel::KeyEvent (int iKeydown)
	{
		const Uint8 *state = SDL_GetKeyboardState(NULL);	
		bool bTextinput;
		bTextinput = false;
		while (SDL_PollEvent(&event)) {

			if (event.type == SDL_TEXTINPUT)
			{
				unsigned char* buffer;
				buffer = (unsigned char*)event.text.text;

				mText += UTF8toASCII(buffer);
				bTextinput = true;
			}

		}
	
		if (state[SDL_SCANCODE_ESCAPE])
		{
			CancelChat();
		
		}
		if (state[SDL_SCANCODE_BACKSPACE])
		{
			if (iKeydown && !bTextinput)
			{
				if (mText.length() > 0)
				{
					mText.erase(mText.length() - 1, mText.length());
				}
			}
			
		}
		if (state[SDL_SCANCODE_RETURN])
		{
			std::string theCommand;

			theCommand += mChatMode;

			theCommand += " \"";

			// Replace all ';' characters with ':' characters since we can't have
			// ';' characters on a console message.

			for (unsigned int i = 0; i < mText.length(); ++i)
			{
				if (mText[i] == ';')
				{
					mText[i] = ':';
				}
			}

			theCommand += mText;

			theCommand += "\"";

			//say_x "the message here" instead of 
			//say_x the message here (ever word was treated as another argument)
			gEngfuncs.pfnClientCmd((char*)theCommand.c_str());

			CancelChat();
		}
	}
