### ISSUE TITLE
ns version does not match

### ISSUE THREAD

**Issue by stefanofabi** [ENSL/NS#77]
Hi, I have installed the latest release ns_v322_full.zip using linux ubuntu 16.04, metamod 1.21p and hlds build 8308

The problem is that when I raise the server it appears in favorites as the game name "NS 3.2.0" when in fact I have installed "NS 3.2.2" or some servers appear "NS 3.2.1"

Any solution?

Thanks!

**Comment by jirikivaari** [comment]
Yes, the version has not been updated.

**Comment by pierow** [comment]
The above changes don't change from 3.2.1, they change 3.2 version numbers.  The issue is likely to do with how the linux server binaries were built and how the build configs have balance.txt disabled or due to some plugin running on the servers people are using.  I haven't fully investigated it.  Running a dedicated windows server on my machine correctly reports 3.2.2.
