### ISSUE TITLE
Onos devour gets displayed as Babblers 

### ISSUE THREAD

**Issue by Bacsu** [ENSL/NS#88]
Description:
--
if you turn weapon fast switch off the weapon_devour has the babblers symbol (left top corner of the image)

Tested with:
--
Client: 3.2.2 Windows
Protocol version 48
Exe version 1.1.2.2/Stdio (valve)
Exe build: 19:53:27 Aug  3 2020 (8684)

Server: 3.2.1 Linux (current ENSL UK server) and
version :  48/1.1.2.2/Stdio 8308 secure  (70)

Server: 3.2.2 Windows
version :  48/1.1.2.2 8684 secure  (70)

How to reproduce:
--
1. Turn weapon fastswitch off
2. evolve to onos with cheats 0 or 1. 
3. choose weaponslot 2 

![20210108234606_1](https://user-images.githubusercontent.com/17541915/104072732-47a4cd00-520c-11eb-9db0-b7823232d41e.jpg)

**Comment by pierow** [comment]
The sprite for this is either 320w.spr or 320w-s.spr, which contains babblers instead of devour.  The 640aw sprites have higher res images and include devour, but they're in multiple separate files.  It might be worth using the higher res sprites for each of these. I haven't looked into where these are loaded in the code yet.
